kind: pipeline
type: kubernetes
name: Build Classroom Video Store App
service_account_name: default

metadata:
  namespace: drone

trigger:
  branch:
    - main
  event:
    exclude:
      - pull_request

steps:
- name: set-tag-app
  image: python:3.9
  environment:
    DRONE: "true"
  commands:
  - echo -n v$DRONE_BUILD_NUMBER,app-latest > .tags
  - cat .tags

- name: docker-build-app
  image: plugins/docker
  when:
    branch:
    - main
    event:
      exclude:
      - pull_request
  settings:
    dockerfile: deployment/app.dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: wildflowerschools/wf-classroom-video-store
    cache_from: wildflowerschools/wf-classroom-video-store:app-latest

---
kind: pipeline
type: kubernetes
name: Build Classroom Video Store CLI
service_account_name: default

metadata:
  namespace: drone

trigger:
  branch:
    - main
  event:
    exclude:
      - pull_request

steps:
  - name: set-tag-cli
    image: python:3.9
    environment:
      DRONE: "true"
    commands:
      - echo -n cli-v$DRONE_BUILD_NUMBER,cli-latest > .tags
      - cat .tags

  - name: docker-build-cli
    image: plugins/docker
    when:
      branch:
        - main
      event:
        exclude:
          - pull_request
    settings:
      dockerfile: deployment/cli.dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: wildflowerschools/wf-classroom-video-store
      cache_from: wildflowerschools/wf-classroom-video-store:cli-latest


services:
 - name: docker
   image: docker:dind
   privileged: true
   volumes:
     - name: dockersock
       path: /var/run

volumes:
 - name: dockersock
   temp: {}
