---
apiVersion: v1
kind: Secret
metadata:
  name: video-storage-password
  namespace: video-service
type: Opaque
stringData:
  password: apeshitcraycraydollarstorepants

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-database
  namespace: video-service


---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: video-storage-mongodb
  namespace: video-service
spec:
  members: 3
  type: ReplicaSet
  version: "5.0.0"
  security:
    authentication:
      modes: ["SCRAM"]
    roles: # custom roles are defined here
      - role: video_io
        db: video_storage
        privileges:
          - resource:
              db: "video_storage"
              collection: "" # an empty string indicates any collection
            actions:
              - changeStream
              - collStats
              - convertToCapped
              - createCollection
              - dbHash
              - dbStats
              - dropCollection
              - createIndex
              - dropIndex
              - find
              - insert
              - killCursors
              - listIndexes
              - listCollections
              - remove
              - renameCollectionSameDB
              - update
        roles: []
  users:
    - name: wildflower-tech
      db: admin
      passwordSecretRef:
        name: video-storage-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: video_io
          db: video_storage
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
